const yargs = require('yargs')

const argv = yargs
  .strict()
  .demandCommand(1, 'You need to select at least one command to use this tool')
  .command(require('./commands/deviceList'))
  .command(require('./commands/deviceListSyncItems'))
  .command(require('./commands/deviceRemoveSyncItem'))
  .command(require('./commands/fixGenreTags'))
  .command(require('./commands/lyrics'))
  .command(require('./commands/playlistAlbums'))
  .command(require('./commands/playlistPaths'))
  .command(require('./commands/playlistUrls'))
  .command(require('./commands/serverList'))
  .parse()
